version: "3.7"
services:
    mysql:
        image: mysql:5.6
        ports:
            - 3306:3306
        networks:
            - modules
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: modules
            MYSQL_USER: modules
            MYSQL_PASSWORD: secret
networks:
    modules: 
        name: 'modules'